### ISSUE TITLE
moneyless.info is down!

### ISSUE THREAD

**Issue by guaka** [hackers4peace/moneyless.info#8]
moneyless.info is down! how to fix it?

DNS is pointing to 194.150.168.83 now

**Comment by guaka** [comment]
I'm playing with hosting websites on S3, I can try to set up this one on there as well

**Comment by elf-pavlik** [comment]
please see #7 or feel free to deploy it wherever you like :) thanks!

**Comment by guaka** [comment]
ok, closing this one
